server:
  port: 10003
spring:
  application:
    name: quartz-test
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz-center?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    initial-size: 10  # ?????
    min-idle: 10  # ?????
    max-active: 20  # ?????
    max-wait: 60000  # ?????????????
    time-between-eviction-runs-millis: 60000  # ???????????????????????????????
    min-evictable-idle-time-millis: 300000  # ?????????????????????????
    test-while-idle: true  # ???????????????
    test-on-borrow: false  # ??????????????????
    test-on-return: false  # ?????????????????
    filters: config,wall,stat  # ?????????filters????????sql?????'wall'?????
    poolPreparedStatements: true # ??PSCache??????????PSCache???
    MaxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 50
    # ??connectProperties?????mergeSql????SQL??
    connectionProperties: druid.stat.slowSqlMillis=500;druid.stat.logSlowSql=true;config.decrypt=false
  quartz:
    job-store-type: jdbc
    jdbc:
      # ????????
      initialize-schema: always  # always never
